config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  validates :make, presence: true
  validates :model, presence: true
  validates :year, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.page(params[:page])
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:make, :model, :year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FuelEconomy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<%= paginate @vehicles %>

<table>
  <thead>
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.make %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.year %></td>
        <td><%= link_to 'Show', vehicle %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @vehicle.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @vehicle.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @vehicle.year %>
</p>

<p>
  <strong>Barrels of Gas Per Year:</strong>
  <%= @vehicle.annuel_barrels %>
</p>

<p>
  <strong>MPG City:</strong>
  <%= @vehicle.city_mpg %>
</p>

<p>
  <strong>MPG Combined:</strong>
  <%= @vehicle.combined_mpg %>
</p>

<p>
  <strong>Annuel Fuel Cost:</strong>
  <%= @vehicle.annuel_fuel_cost %>
</p>

<p>
  <strong>MPG Highway:</strong>
  <%= @vehicle.highway_mpg %>
</p>

<p>
  <strong>You Save Spend:</strong>
  <%= @vehicle.you_save_spend %>
</p>

<%= link_to 'Back', vehicles_path %>